const spriteList = {
	default:{
    spriteName: 'default mario',
		spriteCommand:'!hype spriteName',
		spritePath:'sprites/default_sprite.png', 
		frameCount:3,
		spriteWidth:94,
		spriteHeight:101,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
	},
	//////////////////// SHELLS ///////////////////
    gShell:{
        spriteName: 'Green Shell',
		spriteCommand:'!hype gShell',
		spritePath:'sprites/gshell.png', 
		frameCount:4,
		spriteWidth:110,
		spriteHeight:110,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
    dShell:{
        spriteName: 'Disco Shell',
		spriteCommand:'!hype dShell',
		spritePath:'sprites/dshell.png', 
		frameCount:8,
		spriteWidth:110,
		spriteHeight:110,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
    rShell:{
        spriteName: 'Red Shell',
		spriteCommand:'!hype rShell',
		spritePath:'sprites/rshell.png', 
		frameCount:4,
		spriteWidth:110,
		spriteHeight:110,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
    bShell:{
        spriteName: 'Blue Shell',
		spriteCommand:'!hype bShell',
		spritePath:'sprites/bshell.png', 
		frameCount:4,
		spriteWidth:110,
		spriteHeight:110,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
	//////////////// SHY GUYS ///////////
    shyguy_red:{
        spriteName: 'shyguy_red',
		spriteCommand:'!hype shyguy_',
		spritePath:'sprites/shyguy_red.png', 
		frameCount:4,
		spriteWidth:96,
		spriteHeight:105,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
    shyguy_green:{
        spriteName: 'shyguy_green',
		spriteCommand:'!hype shyguy_',
		spritePath:'sprites/shyguy_green.png', 
		frameCount:4,
		spriteWidth:96,
		spriteHeight:105,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
    shyguy_grey:{
        spriteName: 'shyguy_grey',
		spriteCommand:'!hype shyguy_',
		spritePath:'sprites/shyguy_grey.png', 
		frameCount:4,
		spriteWidth:96,
		spriteHeight:105,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
    shyguy_blue:{
        spriteName: 'shyguy_blue',
		spriteCommand:'!hype shyguy_',
		spritePath:'sprites/shyguy_blue.png', 
		frameCount:4,
		spriteWidth:96,
		spriteHeight:105,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
	///////////////// YOSHIS ///////////////////
    yoshiblue:{
        spriteName: 'YoshiB',
		spriteCommand:'!hype yoshi',
		spritePath:'sprites/yoshiblue.png', 
		frameCount:10,
		spriteWidth:109,
		spriteHeight:120,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
    yoshigreen:{
        spriteName: 'YoshiG',
		spriteCommand:'!hype yoshi',
		spritePath:'sprites/yoshigreen.png', 
		frameCount:10,
		spriteWidth:109,
		spriteHeight:120,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
    yoshilightblue:{
        spriteName: 'YoshiLB',
		spriteCommand:'!hype yoshi',
		spritePath:'sprites/yoshilightblue.png', 
		frameCount:10,
		spriteWidth:109,
		spriteHeight:120,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
    yoshiorange:{
        spriteName: 'YoshiO',
		spriteCommand:'!hype yoshi',
		spritePath:'sprites/yoshiorange.png', 
		frameCount:10,
		spriteWidth:109,
		spriteHeight:120,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
    yoshipurple:{
        spriteName: 'YoshiP',
		spriteCommand:'!hype yoshi',
		spritePath:'sprites/yoshipurple.png', 
		frameCount:10,
		spriteWidth:109,
		spriteHeight:120,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
    yoshired:{
        spriteName: 'YoshiR',
		spriteCommand:'!hype yoshi',
		spritePath:'sprites/yoshired.png', 
		frameCount:10,
		spriteWidth:109,
		spriteHeight:120,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
    yoshiteal:{
        spriteName: 'YoshiT',
		spriteCommand:'!hype yoshi',
		spritePath:'sprites/yoshiteal.png', 
		frameCount:10,
		spriteWidth:109,
		spriteHeight:120,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
    yoshiyellow:{
        spriteName: 'YoshiY',
		spriteCommand:'!hype yoshi',
		spritePath:'sprites/yoshiyellow.png', 
		frameCount:10,
		spriteWidth:109,
		spriteHeight:120,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
	///////////////////////////////////////////////////////////
    supersecretducktankkag:{
        spriteName: 'supersecretducktank',
		spriteCommand:'!hype supersecretducktankkag',
		spritePath:'sprites/supersecretducktank.png', 
		frameCount:4,
		spriteWidth:112,
		spriteHeight:112,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: true,
    },
	cupheadplane:{
        spriteName: 'cuphead_Plane',
		spriteCommand:'!hype cupheadplane',
		spritePath:'sprites/cupheadplane.png', 
		frameCount:4,
		spriteWidth:111,
		spriteHeight:1000,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    shell:{
        spriteName: 'Random Shell',
		spriteCommand:'!hype shell',
		spritePath:'sprites/dshell.png', 
		frameCount:4,
		spriteWidth:110,
		spriteHeight:110,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    shyguy:{
        spriteName: 'Shy Guy',
		spriteCommand:'!hype shyguy',
		spritePath:'sprites/shyguy_red.png', 
		frameCount:4,
		spriteWidth:96,
		spriteHeight:105,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    greg:{
        spriteName: 'greg',
		spriteCommand:'!hype greg',
		spritePath:'sprites/greg.png', 
		frameCount:120,
		spriteWidth:64,
		spriteHeight:114,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
    wart:{
        spriteName: 'wart',
		spriteCommand:'!hype wart',
		spritePath:'sprites/wart.png', 
		frameCount:129,
		spriteWidth:43,
		spriteHeight:122,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: true,
		secret: false,
    },
    supersanic:{
        spriteName: 'supersanic2',
		spriteCommand:'!hype supersanic',
		spritePath:'sprites/supersanic.png', 
		frameCount:10,
		spriteWidth:122,
		spriteHeight:100,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    sanic:{
        spriteName: 'sanic',
		spriteCommand:'!hype sanic',
		spritePath:'sprites/sanic.png', 
		frameCount:24,
		spriteWidth:127,
		spriteHeight:110,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    trace:{
        spriteName: 'Trace-fix',
		spriteCommand:'!hype trace',
		spritePath:'sprites/trace.png', 
		frameCount:8,
		spriteWidth:96,
		spriteHeight:105,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    pizzarat:{
        spriteName: 'Pizza Rat',
		spriteCommand:'!hype pizzarat',
		spritePath:'sprites/rat.png', 
		frameCount:10,
		spriteWidth:246,
		spriteHeight:88,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    tails:{
        spriteName: 'Tails',
		spriteCommand:'!hype tails',
		spritePath:'sprites/tails.png', 
		frameCount:8,
		spriteWidth:129,
		spriteHeight:96,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    megaman:{
        spriteName: 'MegaMan',
		spriteCommand:'!hype megaman',
		spritePath:'sprites/megaman.png', 
		frameCount:3,
		spriteWidth:148,
		spriteHeight:120,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    shovelknight:{
        spriteName: 'Shovel Knight',
		spriteCommand:'!hype shovelknight',
		spritePath:'sprites/shovel.png', 
		frameCount:5,
		spriteWidth:120,
		spriteHeight:120,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    kirby:{
        spriteName: 'Kirby',
		spriteCommand:'!hype kirby',
		spritePath:'sprites/kirby.png', 
		frameCount:11,
		spriteWidth:117,
		spriteHeight:200,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    contra:{
        spriteName: 'Contra',
		spriteCommand:'!hype contra',
		spritePath:'sprites/contra.png', 
		frameCount:6,
		spriteWidth:58,
		spriteHeight:101,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    mariocape:{
        spriteName: 'Mario Cape',
		spriteCommand:'!hype mariocape',
		spritePath:'sprites/mariocape.png', 
		frameCount:3,
		spriteWidth:93,
		spriteHeight:100,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: true,
    },
    wario:{
        spriteName: 'Wario',
		spriteCommand:'!hype wario',
		spritePath:'sprites/wario.png', 
		frameCount:18,
		spriteWidth:117,
		spriteHeight:100,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: true,
    },
    bombert:{
        spriteName: 'Bombert',
		spriteCommand:'!hype bombert',
		spritePath:'sprites/bombert.png', 
		frameCount:8,
		spriteWidth:136,
		spriteHeight:120,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    cloud:{
        spriteName: 'Cloud',
		spriteCommand:'!hype cloud',
		spritePath:'sprites/cloud.png', 
		frameCount:3,
		spriteWidth:130,
		spriteHeight:130,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    robin:{
        spriteName: 'Robin',
		spriteCommand:'!hype robin',
		spritePath:'sprites/robin.png', 
		frameCount:10,
		spriteWidth:130,
		spriteHeight:130,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    bomberman:{
        spriteName: 'Bomberman',
		spriteCommand:'!hype bomberman',
		spritePath:'sprites/bomberman.png', 
		frameCount:3,
		spriteWidth:120,
		spriteHeight:120,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    diddykong:{
        spriteName: 'Diddy Kong',
		spriteCommand:'!hype diddykong',
		spritePath:'sprites/diddykong.png', 
		frameCount:15,
		spriteWidth:107,
		spriteHeight:120,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
    yoshi:{
        spriteName: 'Yoshi',
		spriteCommand:'!hype yoshi',
		spritePath:'sprites/yoshigreen.png', 
		frameCount:10,
		spriteWidth:109,
		spriteHeight:120,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },	
	goombert:{
        spriteName: 'Little Goombert',
		spriteCommand:'!hype goombert',
		spritePath:'sprites/littleGoomba.png', 
		frameCount:2,
		spriteWidth:76,
		spriteHeight:98,
		roleRestrictions: ["Viewer","Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Everyone',
		hidden: false,
		secret: false,
    },
	/////////////////////////////// TIER 1 CUT OFF ////////////////////////////////////////
    alucard:{
        spriteName: 'Alucard',
		spriteCommand:'!hype alucard',
		spritePath:'sprites/alucard.png', 
		frameCount:9,
		spriteWidth:130,
		spriteHeight:130,
		roleRestrictions: ["Streamer","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Tier 1 Sub',
		hidden: false,
		secret: false,
    },
	alucard2:{
        spriteName: 'Alucard2',
		spriteCommand:'!hype alucard2',
		spritePath:'sprites/alucard-2.png', 
		frameCount:16,
		spriteWidth:100,
		spriteHeight:117,
		roleRestrictions: ["Streamer","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Tier 1 Sub',
		hidden: false,
		secret: false,
    },
    toadette:{
        spriteName: 'Toadette',
		spriteCommand:'!hype toadette',
		spritePath:'sprites/toadette.png', 
		frameCount:3,
		spriteWidth:120,
		spriteHeight:120,
		roleRestrictions: ["Streamer","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Tier 1 Sub',
		hidden: false,
		secret: false,
    },
    hollowknight:{
        spriteName: 'Hollow Knight',
		spriteCommand:'!hype hollowknight',
		spritePath:'sprites/hk.png', 
		frameCount:8,
		spriteWidth:60,
		spriteHeight:116,
		roleRestrictions: ["Streamer","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Tier 1 Sub',
		hidden: false,
		secret: false,
    },
    hornet:{
        spriteName: 'Hornet',
		spriteCommand:'!hype hornet',
		spritePath:'sprites/hornet.png', 
		frameCount:3,
		spriteWidth:91,
		spriteHeight:110,
		roleRestrictions: ["Streamer","Subscriber","Tier 1 Sub","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Tier 1 Sub',
		hidden: false,
		secret: false,
    },
	/////////////////////////////// TIER 2 CUT OFF ////////////////////////////////////////
    zote:{
        spriteName: 'Zote',
		spriteCommand:'!hype zote',
		spritePath:'sprites/zote.png', 
		frameCount:4,
		spriteWidth:148,
		spriteHeight:137,
		roleRestrictions: ["Streamer","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Tier 2 Sub',
		hidden: false,
		secret: false,
    },
    dangil:{
        spriteName: 'Dangil',
		spriteCommand:'!hype dangil',
		spritePath:'sprites/dangil.png', 
		frameCount:3,
		spriteWidth:120,
		spriteHeight:120,
		roleRestrictions: ["Streamer","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Tier 2 Sub',
		hidden: false,
		secret: false,
    },
    penitent:{
        spriteName: 'Penitent',
		spriteCommand:'!hype penitent',
		spritePath:'sprites/pen.png', 
		frameCount:14,
		spriteWidth:122,
		spriteHeight:120,
		roleRestrictions: ["Streamer","Tier 2 Sub","Tier 3 Sub"],
		useableBy: 'Tier 2 Sub',
		hidden: false,
		secret: false,
    },
	/////////////////////////////// TIER 3 CUT OFF ////////////////////////////////////////
    snake:{
        spriteName: 'Snake',
		spriteCommand:'!hype snake',
		spritePath:'sprites/snake.png', 
		frameCount:19,
		spriteWidth:152,
		spriteHeight:114,
		roleRestrictions: ["Streamer","Tier 3 Sub"],
		useableBy: 'Tier 3 Sub',
		hidden: false,
		secret: false,
    },
	cloud2:{
        spriteName: 'Cloud2',
		spriteCommand:'!hype cloud2',
		spritePath:'sprites/cloud-2.png', 
		frameCount:25,
		spriteWidth:100,
		spriteHeight:285,
		roleRestrictions: ["Streamer","Tier 3 Sub"],
		useableBy: 'Tier 3 Sub',
		hidden: false,
		secret: false,
    },
	/////////////////////////////// DANGIL ONLY!! /////////////////////////////////
	dangilgoombert:{
        spriteName: 'Big Goombert',
		spriteCommand:'!hype dangilGoombert',
		spritePath:'sprites/bigGoomba.png', 
		frameCount:2,
		spriteWidth:195,
		spriteHeight:251,
		roleRestrictions: ["Streamer"],
		useableBy: 'Dangil',
		hidden: false,
		secret: false,
    },
};
module.exports = spriteList;